### ISSUE TITLE
OpenAI Context Window Error 

### ISSUE THREAD

**Issue by krrishdholakia** [Hadhzy/slodon#22]
Hi @Hels15, 

Faced a ton of context window errors while using agents. 

Would recommend wrapping the openai base with something like `reliableGPT`. 

```
from reliablegpt import reliableGPT
openai.ChatCompletion.create = reliableGPT(openai.ChatCompletion.create, user_email=...)
```

Source: https://github.com/BerriAI/reliableGPT

**Comment by Hels15** [comment]
Well, how would I know?
